general:
  database:
    type: postgres
    host: localhost
    user: username
    password: password
    port: 5432
    db: database
    sslmode: allow
    url: postgresql://username:password@postgres:5432/database?sslmode=disable